# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171127_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
