# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_trip_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicles'),
        ),
    ]
