# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171128_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_address',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
