# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171128_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='backend.VehicleBrand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='backend.VehicleModel'),
        ),
    ]
