# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171128_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
