# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171201_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='time_arrive',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='time_pickup',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
