# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:11
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_profile_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.TextField(blank=True, verbose_name=backend.models.VehicleYear),
        ),
    ]
