# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20171207_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Area'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Scheduler'),
        ),
    ]
